// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sk.jazzman.callanalyzer.domain;

import org.springframework.beans.factory.annotation.Configurable;
import sk.jazzman.callanalyzer.domain.CallType;

privileged aspect CallType_Roo_Configurable {
    
    declare @type: CallType: @Configurable;
    
}
