// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package sk.jazzman.callanalyzer.domain;

import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;
import sk.jazzman.callanalyzer.domain.CAUser;
import sk.jazzman.callanalyzer.domain.CallType;
import sk.jazzman.callanalyzer.domain.Log;
import sk.jazzman.callanalyzer.domain.LogDataOnDemand;

privileged aspect LogDataOnDemand_Roo_DataOnDemand {
    
    declare @type: LogDataOnDemand: @Component;
    
    private Random LogDataOnDemand.rnd = new SecureRandom();
    
    private List<Log> LogDataOnDemand.data;
    
    public Log LogDataOnDemand.getNewTransientLog(int index) {
        Log obj = new Log();
        setCallNumber(obj, index);
        setCallType(obj, index);
        setDuration(obj, index);
        setId(obj, index);
        setImportTime(obj, index);
        setOwner(obj, index);
        setStartCall(obj, index);
        return obj;
    }
    
    public void LogDataOnDemand.setCallNumber(Log obj, int index) {
        String callNumber = "callNumber_" + index;
        obj.setCallNumber(callNumber);
    }
    
    public void LogDataOnDemand.setCallType(Log obj, int index) {
        CallType callType = null;
        obj.setCallType(callType);
    }
    
    public void LogDataOnDemand.setDuration(Log obj, int index) {
        Integer duration = new Integer(index);
        if (duration < 0) {
            duration = 0;
        }
        obj.setDuration(duration);
    }
    
    public void LogDataOnDemand.setId(Log obj, int index) {
        Long id = new Integer(index).longValue();
        obj.setId(id);
    }
    
    public void LogDataOnDemand.setImportTime(Log obj, int index) {
        Date importTime = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setImportTime(importTime);
    }
    
    public void LogDataOnDemand.setOwner(Log obj, int index) {
        CAUser owner = null;
        obj.setOwner(owner);
    }
    
    public void LogDataOnDemand.setStartCall(Log obj, int index) {
        Date startCall = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setStartCall(startCall);
    }
    
    public Log LogDataOnDemand.getSpecificLog(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Log obj = data.get(index);
        Long id = obj.getId_();
        return Log.findLog(id);
    }
    
    public Log LogDataOnDemand.getRandomLog() {
        init();
        Log obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId_();
        return Log.findLog(id);
    }
    
    public boolean LogDataOnDemand.modifyLog(Log obj) {
        return false;
    }
    
    public void LogDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Log.findLogEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Log' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Log>();
        for (int i = 0; i < 10; i++) {
            Log obj = getNewTransientLog(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
